# Generated by Django 4.1 on 2023-10-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestJournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_je_no', models.IntegerField(verbose_name='仕訳番号')),
                ('t_row_no', models.IntegerField(verbose_name='仕訳行番号')),
                ('t_debit_credit', models.CharField(choices=[('1', '借方'), ('2', '貸方')], max_length=1, verbose_name='貸借区分')),
                ('t_account_code', models.IntegerField(verbose_name='科目コード')),
                ('t_amount', models.IntegerField(default=0, verbose_name='金額（税抜）')),
            ],
            options={
                'db_table': 'TestJournalEntry',
            },
        ),
    ]
