# Generated by Django 4.1 on 2023-10-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code_id', models.CharField(max_length=5, verbose_name='勘定科目CD')),
                ('account_name', models.CharField(max_length=25, verbose_name='勘定科目名')),
                ('classification_code_id', models.CharField(max_length=5, verbose_name='区分CD')),
                ('classification_name', models.CharField(max_length=25, verbose_name='区分名')),
                ('fs_display_classification_code_id', models.CharField(max_length=5, verbose_name='決算書表示区分CD')),
                ('fs_display_classification_name', models.CharField(max_length=25, verbose_name='決算書表示区分名')),
                ('opening_balance', models.IntegerField(verbose_name='期首残高')),
            ],
            options={
                'db_table': 'AccountingCode',
            },
        ),
        migrations.CreateModel(
            name='DebitCredit',
            fields=[
                ('debit_credit_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='貸借区分CD')),
                ('debit_credit_name', models.CharField(max_length=2, verbose_name='貸借区分名')),
            ],
            options={
                'db_table': 'DebitCredit',
            },
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('je_no', models.IntegerField(verbose_name='仕訳番号')),
                ('description', models.CharField(max_length=100, verbose_name='摘要')),
            ],
            options={
                'db_table': 'Description',
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('je_no', models.IntegerField(verbose_name='仕訳番号')),
                ('row_no', models.IntegerField(verbose_name='仕訳行番号')),
                ('debit_credit', models.IntegerField(verbose_name='貸借区分')),
                ('account_code', models.CharField(max_length=5, verbose_name='勘定科目CD')),
                ('amount', models.IntegerField(default=0, verbose_name='金額（税抜）')),
            ],
            options={
                'db_table': 'JournalEntry',
            },
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(fields=('je_no', 'row_no'), name='unique_je_id'),
        ),
        migrations.AddConstraint(
            model_name='accountingcode',
            constraint=models.UniqueConstraint(fields=('account_code_id', 'fs_display_classification_code_id'), name='unique_account_id'),
        ),
    ]
